spring:
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coursedb?serverTimezone=GMT%2B8
        username: root
        password: rootroot
    sharding:
      tables:
        course:
          actual-data-nodes: m1.course_$->{1..2}
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: course_$->{cid%2+1}
          key-generator:
            column: cid
            type: SNOWFLAKE
            props:
              worker:
                id: 1
    props:
      sql_show: true
mybatis-plus:
  config-location: ["classpath*:/mapper/**/*.xml"]