spring:
  shardingsphere:
    datasource:
      names: m1,m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coursedb?serverTimezone=GMT%2B8
        username: root
        password: rootroot
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coursedb2?serverTimezone=GMT%2B8
        username: root
        password: rootroot
    sharding:
      tables:
        course:
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
#          database-strategy:
#            hint:
#              algorithm-class-name: com.example.shardingspheredemo.algorithm.MyHintTableShardingAlgorithm
          table-strategy:
            hint:
              algorithm-class-name: com.example.shardingspheredemo.algorithm.MyHintTableShardingAlgorithm
          key-generator:
            column: cid
            type: SNOWFLAKE
            props:
              worker:
                id: 1
        t_dict:
          key-generator:
            column: dict_id
            type: SNOWFLAKE
      broadcast-tables: t_dict

    props:
      sql:
        show: true
mybatis-plus:
  config-location: ["classpath*:/mapper/**/*.xml"]