spring:
  shardingsphere:
    datasource:
      names: m1,m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coursedb?serverTimezone=GMT%2B8
        username: root
        password: rootroot
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coursedb2?serverTimezone=GMT%2B8
        username: root
        password: rootroot
    sharding:
      tables:
        course:
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
#          database-strategy:
#            hint:
#              algorithm-class-name: com.example.shardingspheredemo.algorithm.MyHintTableShardingAlgorithm
          table-strategy:
            hint:
              algorithm-class-name: com.example.shardingspheredemo.algorithm.MyHintTableShardingAlgorithm
          key-generator:
            column: cid
            type: SNOWFLAKE
            props:
              worker:
                id: 1
        t_dict:
          actual-data-nodes: m1.t_dict_$->{1..2}
          key-generator:
            column: dict_id
            type: SNOWFLAKE
            props:
              worker:
                id:1
          table-strategy:
            inline:
              sharding-column: cstatus
              algorithm-expression: t_dict_$->{cstatus.toInteger()%2+1}

        user:
          actual-data-nodes: m1.t_user_$->{1..2}
          key-generator:
            column: user_id
            type: SNOWFLAKE
            props:
              worker:
                id:1
          table-strategy:
            inline:
              sharding-column: ustatus
              algorithm-expression: t_user_$->{ustatus.toInteger()%2+1}
#      broadcast-tables: t_dict
      binding-tables[0]: user,t_dict

    props:
      sql:
        show: true
mybatis-plus:
  config-location: ["classpath*:/mapper/**/*.xml"]